---
name: flake8
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Flake8

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies and run Flake8
        run: |
          python -m pip install flake8
          flake8
