---
name: unittests
on: [push, pull_request]
  
jobs:
  unittest:
    runs-on: ubuntu-latest
    name: Unittest

    strategy:
      matrix:
        python-version:
          [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: |
          python -m pip install -r requirements_dev.txt
          python -m unittest
